# Generated by Django 2.0.5 on 2020-06-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'BD'), (2, 'BDM'), (3, 'CM')]),
        ),
    ]
